[build]
  publish = "."

[[redirects]]
  from = "/company"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/diagnostic"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/google"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/claude"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/openai"
  to = "/app.html"
  status = 200
